package com.manishm.mobilespec

import com.manishm.mobilespec.engine.PhasePolicy

/** Generated by tools/export_android_policy.py from a fully gated device sweep. */
internal object BundledPhasePolicy {
    const val status = "enabled: pp8-tg2 from report 7afd9ae000d5"
    val value = PhasePolicy(
        baselineDecodeThreads = 8,
        baselinePrefillThreads = 8,
        decodeThreads = 2,
        prefillThreads = 8,
        profileIdentitySha256 = "fabc6b3dd1fb6f2eea7c0fe48fd5ce0b0a45ae2fa244d8fa16622ddb1557f0e6",
        deviceFingerprintSha256 = "21af563364372fb1a807f56aa981a621f76791a43e9e148249a90ea546c08b38",
        deviceModel = "24094RAD4I",
        socModel = "MT6855",
        benchmarkBinarySha256 = "459de42359a7abc37ac1e8b0df0ef20b54175d6e09b1d65dbeedd873846fc68b",
        sourceReportSha256 = "7afd9ae000d57bf1bce0e3d38de13d99ffd779a34bbb591f9e41dabffc56a7ab",
        modelSha256 = "fa0390e7c043f89ae1847bd6682d748041a99d4ef3de0e0b27d33b6af97a8be8",
        llamaCommit = "178a6c449371",
        contextSize = 512,
        workloadClass = "interactive-chat-decode-weighted",
    )
}
