package com.manishm.mobilespec

import com.manishm.mobilespec.engine.PhasePolicy

/** Generated by tools/export_android_policy.py from a fully gated device sweep. */
internal object BundledPhasePolicy {
    const val status = "disabled: native binary changed; final device re-sweep pending"
    val value: PhasePolicy? = null
}
