#!/usr/bin/env python3
"""Export one fully gated autotune report as the APK's bundled phase policy.

The generated Kotlin source is deliberately disabled on every validation failure,
so a failed or malformed replacement report cannot leave an older winner active.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    REPO_ROOT
    / "app/src/main/java/com/manishm/mobilespec/BundledPhasePolicy.kt"
)
REQUIRED_GATES = (
    "allCandidatesMeasured",
    "baselineMeasured",
    "thermallyStable",
    "runOrderNeutral",
    "winnerIsStable",
    "beatsStockDefault",
)
HEX_SHA256 = re.compile(r"^[0-9a-fA-F]{64}$")
HEX_COMMIT = re.compile(r"^[0-9a-fA-F]{7,40}$")
SUPPORTED_WORKLOAD = "interactive-chat-decode-weighted"


class PolicyExportError(ValueError):
    pass


def _required_dict(value: Any, name: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise PolicyExportError(f"{name} is missing or is not an object")
    return value


def _positive_int(value: Any, name: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
        raise PolicyExportError(f"{name} must be a positive integer")
    return value


def _sha256(value: Any, name: str) -> str:
    if not isinstance(value, str) or not HEX_SHA256.fullmatch(value):
        raise PolicyExportError(f"{name} must be a 64-character SHA-256")
    return value.lower()


def _text(value: Any, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise PolicyExportError(f"{name} must be a non-empty string")
    return value.strip()


def _kotlin_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def disabled_source(reason: str) -> str:
    return f"""package com.manishm.mobilespec

import com.manishm.mobilespec.engine.PhasePolicy

/** Generated by tools/export_android_policy.py; optimized mode is fail-closed. */
internal object BundledPhasePolicy {{
    const val status = {_kotlin_string('disabled: ' + reason)}
    val value: PhasePolicy? = null
}}
"""


def policy_from_report(report: dict[str, Any], report_sha256: str) -> dict[str, Any]:
    if report.get("schemaVersion") != 1 or report.get("tool") != "autotune":
        raise PolicyExportError("input is not a schemaVersion 1 autotune report")
    if report.get("dryRun") is not False:
        raise PolicyExportError("dry-run reports cannot enable an Android policy")
    if report.get("source") != "sweep" or report.get("verdict") != "autotuned":
        raise PolicyExportError("only a fresh sweep with verdict=autotuned can be exported")

    gates = _required_dict(report.get("gates"), "gates")
    failed = [name for name in REQUIRED_GATES if gates.get(name) is not True]
    if failed:
        raise PolicyExportError("required gates did not pass: " + ", ".join(failed))

    identity_with_hash = _required_dict(report.get("profileIdentity"), "profileIdentity")
    identity = dict(identity_with_hash)
    claimed_identity_sha = _sha256(identity.pop("sha256", None), "profileIdentity.sha256")
    canonical = json.dumps(identity, sort_keys=True, separators=(",", ":"))
    actual_identity_sha = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    if claimed_identity_sha != actual_identity_sha:
        raise PolicyExportError("profile identity hash does not match its canonical contents")

    recommendation = _required_dict(report.get("recommendation"), "recommendation")
    if recommendation.get("source") != "sweep":
        raise PolicyExportError("recommendation was not produced by the fresh sweep")
    candidate_id = _text(recommendation.get("candidateId"), "recommendation.candidateId")
    if not candidate_id.startswith("pp"):
        raise PolicyExportError("winner is not an explicit prefill/decode phase pair")
    if recommendation.get("cpuMask") not in (None, ""):
        raise PolicyExportError("Android runtime cannot export a shared-affinity winner")

    decode_threads = _positive_int(recommendation.get("threads"), "recommendation.threads")
    prefill_threads = _positive_int(
        recommendation.get("threadsBatch"), "recommendation.threadsBatch"
    )
    baseline_decode = _positive_int(
        recommendation.get("baselineThreads"), "recommendation.baselineThreads"
    )
    baseline_prefill = _positive_int(
        recommendation.get("baselineThreadsBatch"),
        "recommendation.baselineThreadsBatch",
    )
    if (decode_threads, prefill_threads) == (baseline_decode, baseline_prefill):
        raise PolicyExportError("phase pair is identical to the measured stock baseline")

    model = _required_dict(report.get("model"), "model")
    device = _required_dict(report.get("device"), "device")
    source_commit = _text(
        identity.get("llamaCppSourceCommit"), "profileIdentity.llamaCppSourceCommit"
    )
    if not HEX_COMMIT.fullmatch(source_commit):
        raise PolicyExportError("llama.cpp source commit is malformed")
    model_sha = _sha256(model.get("sha256"), "model.sha256")
    identity_model_sha = _sha256(
        identity.get("modelSha256"), "profileIdentity.modelSha256"
    )
    if model_sha != identity_model_sha:
        raise PolicyExportError("profile identity model hash does not match the report model")
    workload_class = _text(
        identity.get("workloadClass"), "profileIdentity.workloadClass"
    )
    if workload_class != SUPPORTED_WORKLOAD:
        raise PolicyExportError(f"unsupported Android workload class: {workload_class}")

    return {
        "baselineDecodeThreads": baseline_decode,
        "baselinePrefillThreads": baseline_prefill,
        "decodeThreads": decode_threads,
        "prefillThreads": prefill_threads,
        "profileIdentitySha256": claimed_identity_sha,
        "deviceFingerprintSha256": _sha256(device.get("fingerprint"), "device.fingerprint"),
        "deviceModel": _text(device.get("model"), "device.model"),
        "socModel": _text(device.get("soc"), "device.soc"),
        "benchmarkBinarySha256": _sha256(
            identity.get("binarySha256"), "profileIdentity.binarySha256"
        ),
        "sourceReportSha256": _sha256(report_sha256, "source report SHA-256"),
        "modelSha256": model_sha,
        "llamaCommit": source_commit[:12],
        "contextSize": _positive_int(identity.get("contextSize"), "profileIdentity.contextSize"),
        "workloadClass": workload_class,
        "candidateId": candidate_id,
    }


def enabled_source(policy: dict[str, Any]) -> str:
    status = (
        f"enabled: {policy['candidateId']} from report "
        f"{policy['sourceReportSha256'][:12]}"
    )
    string_fields = (
        "profileIdentitySha256",
        "deviceFingerprintSha256",
        "deviceModel",
        "socModel",
        "benchmarkBinarySha256",
        "sourceReportSha256",
        "modelSha256",
        "llamaCommit",
        "workloadClass",
    )
    rendered = {
        name: _kotlin_string(str(policy[name])) if name in string_fields else str(policy[name])
        for name in policy
        if name != "candidateId"
    }
    return f"""package com.manishm.mobilespec

import com.manishm.mobilespec.engine.PhasePolicy

/** Generated by tools/export_android_policy.py from a fully gated device sweep. */
internal object BundledPhasePolicy {{
    const val status = {_kotlin_string(status)}
    val value = PhasePolicy(
        baselineDecodeThreads = {rendered['baselineDecodeThreads']},
        baselinePrefillThreads = {rendered['baselinePrefillThreads']},
        decodeThreads = {rendered['decodeThreads']},
        prefillThreads = {rendered['prefillThreads']},
        profileIdentitySha256 = {rendered['profileIdentitySha256']},
        deviceFingerprintSha256 = {rendered['deviceFingerprintSha256']},
        deviceModel = {rendered['deviceModel']},
        socModel = {rendered['socModel']},
        benchmarkBinarySha256 = {rendered['benchmarkBinarySha256']},
        sourceReportSha256 = {rendered['sourceReportSha256']},
        modelSha256 = {rendered['modelSha256']},
        llamaCommit = {rendered['llamaCommit']},
        contextSize = {rendered['contextSize']},
        workloadClass = {rendered['workloadClass']},
    )
}}
"""


def export_policy(report_path: Path, output_path: Path) -> dict[str, Any]:
    try:
        raw = report_path.read_bytes()
        report_sha = hashlib.sha256(raw).hexdigest()
        parsed = json.loads(raw)
        report = _required_dict(parsed, "report")
        policy = policy_from_report(report, report_sha)
    except (OSError, json.JSONDecodeError, PolicyExportError) as error:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(disabled_source(str(error)), encoding="utf-8")
        if isinstance(error, PolicyExportError):
            raise
        raise PolicyExportError(str(error)) from error
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(enabled_source(policy), encoding="utf-8")
    return policy


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Export a fully gated autotune report into the Android app"
    )
    parser.add_argument("report", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    try:
        policy = export_policy(args.report, args.output)
    except PolicyExportError as error:
        print(f"disabled Android phase policy: {error}", file=sys.stderr)
        return 2
    print(
        f"exported {policy['candidateId']} to {args.output} "
        f"(report {policy['sourceReportSha256'][:12]})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
